[package]
name = "qtlib"
version = "0.1.0"
authors = ["ZecWallet"]
edition = "2018"

[lib]
name = "hushpaperrust"
crate-type = ["staticlib"]

[dependencies]
libc = "0.2.58"
hushpaperlib = { path = "../../lib" }